[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 5173
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "src/data/*.json"
  ]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
